Repository w3c/mediacapture-main, pull requests merged in 2020-07, with the labels that each got.

#657 In case track is ended, make sure deviceId/groupId are exposed if they were exposed when the track was not ended
  getusermedia.html
Labels: Needs Test

#701 Add best practice on device muting.
  getusermedia.html
Labels: Editors can integrate

#704 Rename Feature Policy section (editorial)
  getusermedia.html
Labels: Editors can integrate

#705 Fix link for toJSON() in MediaDeviceInfo
  getusermedia.html
Labels: editorial

#706 Clarify label may have no identifying info.
  getusermedia.html
Labels: Editors can integrate
