Repository w3c/mediacapture-main, pull requests merged in 2020-12, with the labels that each got.

#753 Adapt GitHub CI to platform change
  .github/workflows/update-respec.yml
Labels: editorial

#731 Add requirements to support downsampling and frame decimation
  getusermedia.html
Labels: Editors can integrate

#755 Update to latest ReSpec version
  respec-w3c.js
Labels: editorial

#743 Improve respec autolinks and mark events as such
  getusermedia.html
  getusermedia.js
Labels: Editors can integrate, editorial

#760 Define behavior when rotating camera.
  getusermedia.html
Labels: Editors can integrate
