Repository w3c/mediacapture-main, pull requests merged in 2020-04, with the labels that each got.

#677 Upgrade to ReSpec 25.4.2
  getusermedia.html
  getusermedia.js
  respec-w3c.js
Labels: editorial

#678 Use more consistent linking practices
  getusermedia.html
  getusermedia.js
Labels: editorial

#679 Update editors list to reflect former editor statuses
  getusermedia.js
Labels: editorial

#681 Remove outdated mentions of Media Capture Task Force
  getusermedia.html
Labels: editorial

#680 Remove outdated mention of usage on insecure contexts
  getusermedia.html
Labels: Editors can integrate, editorial

#687 Remove UUID recommendation for deviceId and groupId.
  getusermedia.html
Labels: Editors can integrate
