Repository w3c/mediacapture-main, pull requests merged in 2022-12, with the labels that each got.

#917 Update to latest ReSpec version 32.4.0
  respec-w3c.js
Labels: editorial, repo-management

#918 Update to latest ReSpec version 32.5.0
  respec-w3c.js
Labels: editorial, repo-management

#912 Allow gUM prompt ahead of focus + deterministic "visible" enumeration wo/focus
  getusermedia.html
Labels: Editors can integrate

#920 Remove duplicate text
  getusermedia.html
Labels: editorial

#921 Update to latest ReSpec version 32.5.1
  respec-w3c.js
Labels: editorial, repo-management

#922 Update to latest ReSpec version 32.6.0
  respec-w3c.js
Labels: editorial, repo-management
