Repository w3c/mediacapture-main, pull requests merged in 2022-06, with the labels that each got.

#889 Update to latest ReSpec version 32.1.8
  respec-w3c.js
Labels: editorial, repo-management

#884 Improve markup for event tables
  getusermedia.html
Labels: editorial

#873 Add source specific handling for creation and cloning of tracks
  getusermedia.html
Labels: Editors can integrate, Needs Test

#891 Update to latest ReSpec version 32.1.10
  respec-w3c.js
Labels: editorial, repo-management
