Repository w3c/mediacapture-main, pull requests merged in 2023-04, with the labels that each got.

#950 Update to latest ReSpec version 32.8.1
  respec-w3c.js
Labels: editorial, repo-management

#948 Replace Values with Type column in Constrainable Properties tables.
  getusermedia.html
Labels: editorial, Editors can integrate

#955 Update to latest ReSpec version 34.0.1
  respec-w3c.js
Labels: editorial, repo-management

#957 Improve markup of definitions and algorithms
  getusermedia.html
  respec-w3c.js
Labels: editorial
