Repository w3c/mediacapture-main, pull requests merged in 2023-02, with the labels that each got.

#926 Split device sanitation note into separate paragraph
  getusermedia.html
Labels: editorial

#929 Update to latest ReSpec version 32.7.0
  respec-w3c.js
Labels: editorial, repo-management

#932 query without deviceId is for access to any device of a kind.
  getusermedia.html
Labels: Editors can integrate

#931 Update to latest ReSpec version 32.7.1
  respec-w3c.js
Labels: editorial, repo-management
